# This is a basic workflow to help you get started with Actions

name: swagger-validate

# Controls when the workflow will run
on:
<<<<<<< HEAD
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
=======

push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  
>>>>>>> 1a44ee00a6057ec52bf22ec58f5a2662f993d1ad
jobs:
  build:
    container: gkarthics/swagger-validate:0.2.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate
      run: validate .
