name: swagger-validate
on:

push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  
  workflow_dispatch:
  
jobs:
  build:
    container: gkarthics/swagger-validate:0.2.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate
      run: validate .
